environment:
  NPM_TOKEN:
    secure: X2j/60HUwEOfKeWKBhULQ5cxY9QDwmahtXeg6GP3bg22TRMT5FrjWGduxZfNKJfD
  DEPLOY_HOOK:
    secure: lgHgjTE7lKmIKHVjnf51q0zxzzmourN5yJMDM5nmvHNe0/sCSYxYQlOtaGyMA+RU+HAtHkHPs0skrZmLksJ4/wD1utUO/GxfKZHB0lcd1bI=

image: Ubuntu

init:
  - nvm use 14
install:
  - npm install
test_script:
  - npm run typecheck
  - npm run lint

skip_branch_with_pr: true

for:
  -
    branches:
      only:
        - /v\d+\.\d+\.\d+/
    skip_non_tags: true
    before_build:
      - npm run build:lib
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - npm publish
    build_script:
      - curl ${DEPLOY_HOOK}
  -
    branches:
      except:
        - /v\d+\.\d+\.\d+/
    build: off
